services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      -  8090:80 # change ip if required
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "ceccafish!"
    depends_on:
      - db
    links:
      - db

  pma:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: "ceccafish!"
      UPLOAD_LIMIT: 50M
    ports:
      - 8091:80
    links:
      - db:db
    volumes:
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    # platform: linux/x86_64  # Uncomment if your machine is running on arm (ex: Apple Silicon processor)
    ports:
      - 3307:3307 # change ip if required
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "ceccafish!"

volumes:
  db_data:
